# Should the plugin be allowed to check for updates?
update-checker: true

# Should debug messages be sent to the console?
debug-mode: false

# Should the plugin send an action bar to players with active cooldowns?
use-action-bar: true
